trigger:
  branches:
    include:     
      - main  

pool:
  name: Default

stages:
- stage: Build
  displayName: 'Build and Test'
  jobs:
  - job: CI
    displayName: 'Continuous Integration'
    steps:
    - task: UseDotNet@2
      displayName: 'Install .NET Core sdk'
      inputs:
        packageType: 'sdk'
        version: '6.9.2'  

    - script: dotnet restore
      displayName: 'Restore dependencies'

    - script: dotnet build --configuration Release
      displayName: 'Build application'

    - script: dotnet test
      displayName: 'Run tests'

- stage: Deploy
  displayName: 'Deploy to Azure Web App'
  jobs:
  - job: CD
    displayName: 'Continuous Deployment'
    steps:
    - task: UseDotNet@2
      displayName: 'Install .NET Core sdk'
      inputs:
        packageType: 'sdk'
        version: '6.9.2'  

    - task: DotNetCoreCLI@2
      displayName: 'Publish to Azure Web App'
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: true

    - task: AzureRmWebAppDeployment@4
      displayName: 'Azure Web App Deploy'
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Azure_DevOps_Service_Connection'
        appType: 'webApp'
        WebAppName: 'Tab-WebApp'
        packageForLinux: '$(Build.ArtifactStagingDirectory)/*/.zip'
        enableCustomDeployment: true
        deploymentMethod: 'zipDeploy'